# generated by datamodel-codegen:
#   filename:  webapp-security-map-minimal.schema.json
#   timestamp: 2026-03-30T19:08:02+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    RootModel,
    confloat,
    conint,
    constr,
)


class SourceMode(StrEnum):
    observed = 'observed'
    inferred = 'inferred'
    merged = 'merged'


class Id(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class NullableString(RootModel[str | None]):
    root: str | None


class StringArray(RootModel[list[str]]):
    root: list[str]


class StringOrNullArray(RootModel[list[str | None]]):
    root: list[str | None]


class CrawlScope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allowed_hosts: StringArray
    allowed_path_prefixes: StringArray


class CrawlerContext(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    run_id: Id
    model_name: NullableString | None
    browser_profile_id: NullableString | None
    notes: NullableString | None


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    target_base_url: constr(min_length=1)
    app_name: NullableString | None
    crawl_started_at: AwareDatetime
    crawl_finished_at: AwareDatetime
    crawl_scope: CrawlScope
    crawler_context: CrawlerContext


class Kind(StrEnum):
    anonymous = 'anonymous'
    authenticated = 'authenticated'
    role_variant = 'role_variant'
    service_account = 'service_account'
    unknown = 'unknown'


class AuthState(StrEnum):
    unauthenticated = 'unauthenticated'
    partial = 'partial'
    authenticated = 'authenticated'
    unknown = 'unknown'


class ViewType(StrEnum):
    page = 'page'
    modal = 'modal'
    drawer = 'drawer'
    tab = 'tab'
    wizard_step = 'wizard_step'
    popup = 'popup'
    embedded_frame = 'embedded_frame'
    unknown = 'unknown'


class Location(StrEnum):
    input = 'input'
    hidden_input = 'hidden_input'
    url_param = 'url_param'
    state = 'state'
    generated = 'generated'
    unknown = 'unknown'


class ParameterDef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1)
    location: Location
    data_type: NullableString | None
    required: bool | None
    example_redacted: Any


class Kind1(StrEnum):
    button = 'button'
    link = 'link'
    form = 'form'
    input = 'input'
    password_input = 'password_input'
    hidden_input = 'hidden_input'
    select = 'select'
    checkbox = 'checkbox'
    radio = 'radio'
    upload = 'upload'
    table_action = 'table_action'
    pagination = 'pagination'
    search_box = 'search_box'
    tab_trigger = 'tab_trigger'
    menu_item = 'menu_item'
    toggle = 'toggle'
    unknown = 'unknown'


class ActionType(StrEnum):
    navigate = 'navigate'
    submit = 'submit'
    mutate = 'mutate'
    upload = 'upload'
    search = 'search'
    filter = 'filter'
    select = 'select'
    open_view = 'open_view'
    close_view = 'close_view'
    download = 'download'
    trigger_background_request = 'trigger_background_request'
    unknown = 'unknown'


class StorageKind(StrEnum):
    cookie = 'cookie'
    local_storage = 'local_storage'
    session_storage = 'session_storage'
    indexeddb = 'indexeddb'
    memory_state = 'memory_state'
    url_param = 'url_param'
    cache_api = 'cache_api'
    service_worker_cache = 'service_worker_cache'
    unknown = 'unknown'


class Persistence(StrEnum):
    request = 'request'
    tab = 'tab'
    browser_session = 'browser_session'
    persistent = 'persistent'
    unknown = 'unknown'


class NamedParam(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1)
    data_type: NullableString | None


class RequestContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    header_names: StringArray
    path_params: list[NamedParam]
    query_params: list[NamedParam]
    body_content_types: StringArray
    body_shape: NullableString | None


class ResponseContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status_codes: list[int]
    header_names: StringArray
    body_content_types: StringArray
    body_shape: NullableString | None


class Protocol(StrEnum):
    http = 'http'
    https = 'https'
    ws = 'ws'
    wss = 'wss'
    sse = 'sse'
    graphql_http = 'graphql_http'
    graphql_ws = 'graphql_ws'
    unknown = 'unknown'


class Method(StrEnum):
    GET = 'GET'
    POST = 'POST'
    PUT = 'PUT'
    PATCH = 'PATCH'
    DELETE = 'DELETE'
    OPTIONS = 'OPTIONS'
    HEAD = 'HEAD'
    WS = 'WS'
    SUBSCRIBE = 'SUBSCRIBE'
    UNKNOWN = 'UNKNOWN'


class RequestInstance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: constr(min_length=1)
    header_names: StringArray
    query_keys: StringArray
    body_keys: StringArray
    body_shape: NullableString | None
    body_example_redacted: Any


class ResponseInstance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status_code: int | None
    header_names: StringArray
    body_shape: NullableString | None
    body_keys: StringArray
    body_example_redacted: Any


class Correlation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    traceparent_present: bool | None
    tracestate_present: bool | None
    request_id_headers: StringArray


class IdentifierField(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1)
    format_hint: NullableString | None
    observed_in_ids: list[Id]


class StepType(StrEnum):
    ui_action = 'ui_action'
    navigation = 'navigation'
    request = 'request'
    response = 'response'
    state_read = 'state_read'
    state_write = 'state_write'
    state_change = 'state_change'
    entity_load = 'entity_load'
    entity_mutation = 'entity_mutation'
    unknown = 'unknown'


class RelationType(StrEnum):
    CONTAINS = 'CONTAINS'
    NAVIGATES_TO = 'NAVIGATES_TO'
    TRIGGERS = 'TRIGGERS'
    CALLS = 'CALLS'
    PRECEDES = 'PRECEDES'
    READS_STATE = 'READS_STATE'
    WRITES_STATE = 'WRITES_STATE'
    REQUIRES_STATE = 'REQUIRES_STATE'
    PRODUCES_STATE = 'PRODUCES_STATE'
    USES_IDENTIFIER = 'USES_IDENTIFIER'
    RETURNS_ENTITY = 'RETURNS_ENTITY'
    REPRESENTS_ENTITY = 'REPRESENTS_ENTITY'
    BELONGS_TO_FLOW = 'BELONGS_TO_FLOW'
    VISIBLE_TO_ACTOR = 'VISIBLE_TO_ACTOR'
    REACHABLE_BY_ACTOR = 'REACHABLE_BY_ACTOR'
    DERIVES_FROM = 'DERIVES_FROM'


class Kind2(StrEnum):
    dom_snapshot = 'dom_snapshot'
    aria_tree = 'aria_tree'
    screenshot = 'screenshot'
    network_log = 'network_log'
    request_capture = 'request_capture'
    response_capture = 'response_capture'
    storage_snapshot = 'storage_snapshot'
    console_log = 'console_log'
    url_observation = 'url_observation'
    model_inference = 'model_inference'
    replay_trace = 'replay_trace'
    unknown = 'unknown'


class Evidence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Id
    kind: Kind2
    source_ref: constr(min_length=1)
    excerpt_redacted: NullableString | None
    timestamp: AwareDatetime | None
    notes: NullableString | None


class BaseWithProvenance(BaseModel):
    id: Id
    source_mode: SourceMode
    confidence: confloat(ge=0.0, le=1.0)
    evidence_refs: list[Id]


class Actor(BaseWithProvenance):
    id: Id
    label: constr(min_length=1)
    kind: Kind
    auth_state: AuthState
    role_labels: StringArray
    parent_actor_id: str | None
    session_capabilities: StringArray
    source_mode: SourceMode
    confidence: confloat(ge=0.0, le=1.0)
    evidence_refs: list[Id]
    notes: NullableString | None


class View(BaseWithProvenance):
    id: Id
    label: constr(min_length=1)
    view_type: ViewType
    canonical_route: constr(min_length=1)
    url_examples: StringArray
    title_text: NullableString | None
    parent_view_id: str | None
    reachable_actor_ids: list[Id]
    required_state_tags: StringArray
    produced_state_tags: StringArray
    entity_ids: list[Id]
    source_mode: SourceMode
    confidence: confloat(ge=0.0, le=1.0)
    evidence_refs: list[Id]
    notes: NullableString | None


class UiElement(BaseWithProvenance):
    id: Id
    view_id: Id
    kind: Kind1
    label: NullableString | None
    selector_hint: NullableString | None
    action_type: ActionType
    parameter_defs: list[ParameterDef]
    reads_state_item_ids: list[Id]
    writes_state_item_ids: list[Id]
    expected_endpoint_ids: list[Id]
    source_mode: SourceMode
    confidence: confloat(ge=0.0, le=1.0)
    evidence_refs: list[Id]
    notes: NullableString | None


class StateItem(BaseWithProvenance):
    id: Id
    storage_kind: StorageKind
    key: constr(min_length=1)
    scope: NullableString | None
    persistence: Persistence
    observed_shape: NullableString | None
    example_redacted: Any
    produced_by_ids: list[Id]
    consumed_by_ids: list[Id]
    source_mode: SourceMode
    confidence: confloat(ge=0.0, le=1.0)
    evidence_refs: list[Id]
    notes: NullableString | None


class Endpoint(BaseWithProvenance):
    id: Id
    protocol: Protocol
    host: NullableString | None
    method: Method
    path_template: constr(min_length=1)
    operation_name: NullableString | None
    request_contract: RequestContract
    response_contract: ResponseContract
    auth_inputs_observed: StringArray
    entity_ids: list[Id]
    source_mode: SourceMode
    confidence: confloat(ge=0.0, le=1.0)
    evidence_refs: list[Id]
    notes: NullableString | None


class ObservedRequest(BaseWithProvenance):
    id: Id
    session_id: Id
    order: conint(ge=0)
    actor_id: Id
    endpoint_id: Id
    initiated_by_ui_element_id: str | None
    preceding_request_id: str | None
    request_instance: RequestInstance
    response_instance: ResponseInstance
    correlation: Correlation
    state_reads: list[Id]
    state_writes: list[Id]
    resulting_view_id: str | None
    resulting_entity_ids: list[Id]
    source_mode: SourceMode
    confidence: confloat(ge=0.0, le=1.0)
    evidence_refs: list[Id]
    notes: NullableString | None


class Entity(BaseWithProvenance):
    id: Id
    kind: constr(min_length=1)
    label: NullableString | None
    identifier_fields: list[IdentifierField]
    attribute_names: StringArray
    source_endpoint_ids: list[Id]
    sink_view_ids: list[Id]
    source_mode: SourceMode
    confidence: confloat(ge=0.0, le=1.0)
    evidence_refs: list[Id]
    notes: NullableString | None


class Flow(BaseWithProvenance):
    id: Id
    name: constr(min_length=1)
    goal: constr(min_length=1)
    actor_ids: list[Id]
    entry_view_id: str | None
    trigger_ui_element_id: str | None
    preconditions: StringArray
    postconditions: StringArray
    step_ids: list[Id]
    entity_ids: list[Id]
    source_mode: SourceMode
    confidence: confloat(ge=0.0, le=1.0)
    evidence_refs: list[Id]
    notes: NullableString | None


class FlowStep(BaseWithProvenance):
    id: Id
    flow_id: Id
    order: conint(ge=0)
    step_type: StepType
    ref_id: Id
    expects_from_step_id: str | None
    produces_state_tags: StringArray
    consumes_state_tags: StringArray
    source_mode: SourceMode
    confidence: confloat(ge=0.0, le=1.0)
    evidence_refs: list[Id]
    notes: NullableString | None


class Session(BaseWithProvenance):
    id: Id
    actor_id: Id
    started_at: AwareDatetime
    ended_at: AwareDatetime | None
    initial_url: NullableString | None
    final_url: NullableString | None
    observed_view_ids: list[Id]
    observed_flow_ids: list[Id]
    observed_request_ids: list[Id]
    source_mode: SourceMode
    confidence: confloat(ge=0.0, le=1.0)
    evidence_refs: list[Id]
    notes: NullableString | None


class Relation(BaseWithProvenance):
    id: Id
    source_id: Id
    relation_type: RelationType
    target_id: Id
    condition: NullableString | None
    source_mode: SourceMode
    confidence: confloat(ge=0.0, le=1.0)
    evidence_refs: list[Id]
    notes: NullableString | None


class WebAppSecurityMapMinimal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_name: Literal['WebAppSecurityMapMinimal']
    schema_version: Literal['1.0']
    metadata: Metadata
    actors: list[Actor]
    views: list[View]
    ui_elements: list[UiElement]
    state_items: list[StateItem]
    endpoints: list[Endpoint]
    observed_requests: list[ObservedRequest]
    entities: list[Entity]
    flows: list[Flow]
    flow_steps: list[FlowStep]
    sessions: list[Session]
    relations: list[Relation]
    evidence: list[Evidence]
